import type { AppState, BuildPhase, Task } from './types';

const now = new Date();
const minutesAgo = (mins: number) => new Date(now.getTime() - mins * 60_000).toISOString();

const scoreTask = (task: Omit<Task, 'priority_score' | 'created_at' | 'updated_at' | 'movement_history'>): Task => ({
  ...task,
  priority_score: Number((((task.impact * task.confidence * task.goal_fit) / task.effort).toFixed(2))),
  movement_history: [
    {
      from: null,
      to: task.status,
      reason: task.source === 'user'
        ? 'Founder added this work to the board so Northstar can score and route it.'
        : 'Task was generated from the current company readout and operating plan.',
      at: minutesAgo(60),
    },
  ],
  created_at: minutesAgo(60),
  updated_at: minutesAgo(5),
});

export const demoState: AppState = {
  workspace: {
    id: 'ws_1',
    name: 'North Star Foundry',
    createdAt: minutesAgo(7_200),
  },
  project: {
    id: 'prj_1',
    workspaceId: 'ws_1',
    name: 'Acme Studio',
    websiteUrl: 'https://acme-studio.com',
    createdAt: minutesAgo(7_100),
  },
  snapshot: {
    id: 'snap_1',
    projectId: 'prj_1',
    capturedAt: minutesAgo(120),
    homepageTitle: 'Strategic design and growth for modern teams',
    homepageSummary: 'The homepage positions the company as a design and growth partner for ambitious teams, but it under-explains who the service is for and what the strongest conversion path should be.',
    pages: [
      {
        url: 'https://acme-studio.com/',
        title: 'Home',
        summary: 'Clear positioning, but weak CTA hierarchy.',
      },
      {
        url: 'https://acme-studio.com/services',
        title: 'Services',
        summary: 'Lists services without tying them to measurable outcomes.',
      },
      {
        url: 'https://acme-studio.com/blog',
        title: 'Blog',
        summary: 'Has the right content channel, but no keyword strategy.',
      },
    ],
  },
  profile: {
    id: 'cmp_1',
    projectId: 'prj_1',
    companyName: 'Acme Studio',
    summary: 'A boutique growth and design studio helping founder-led businesses improve conversion, visibility, and positioning.',
    guessedIcp: 'Founder-led SaaS and service businesses with 1-20 people that need clearer positioning and a repeatable content engine.',
    keyPages: ['Home', 'Services', 'Blog'],
    opportunities: [
      'Homepage copy can sharpen the value proposition and CTA hierarchy.',
      'SEO clusters around founder pain points are underdeveloped.',
      'LinkedIn thought leadership can turn expertise into top-of-funnel demand.',
      'The blog can support comparison and educational search intent.',
    ],
  },
  founderIntake: {
    websiteUrl: 'https://acme-studio.com',
    businessDescription: 'A boutique growth and design studio helping founder-led businesses improve conversion, visibility, and positioning.',
    icp: 'Founder-led SaaS and service businesses with lean teams and inconsistent growth systems.',
    mainGoal: 'Generate more qualified pipeline from content and website improvements.',
    keyChannel: 'SEO, homepage messaging, and founder-led social content',
    whatTried: 'A few blog posts, scattered LinkedIn posts, and ad hoc website updates.',
    priorityWork: 'Build the GTM plan first, then create the first SEO and content tasks.',
    competitors: 'Growth.design, Animalz, and boutique conversion agencies',
    bottleneck: 'conversion',
    authMethod: 'google',
    email: 'founder@acme-studio.com',
  },
  founderSession: {
    authMethod: 'google',
    email: 'founder@acme-studio.com',
    status: 'connected',
    displayName: 'founder@acme-studio.com',
  },
  tasks: [
    scoreTask({
      id: 't1',
      title: 'Audit homepage message hierarchy',
      description: 'Review the hero, benefit stack, and calls-to-action so the homepage explains the company faster and with more conviction.',
      type: 'homepage_copy_suggestion',
      category: 'website',
      channel: 'web',
      outputLabel: 'Homepage copy recommendation',
      executionStage: 'strategy',
      source: 'system',
      status: 'planned',
      impact: 5,
      effort: 2,
      confidence: 4,
      goal_fit: 5,
      rationale: `Why this exists: The homepage is still the highest-signal conversion surface for the company.\nWhy this priority: This is quick to improve and unblocks later SEO and content work.\nBusiness outcome: Sharper messaging should increase qualified contact intent and reduce founder explanation overhead.`,
      dependencies: [],
      actor: 'northstar',
      needsFounderAction: false,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't2',
      title: 'Build keyword cluster around founder-led growth',
      description: 'Group target keywords into SEO clusters focused on positioning, conversion, and content operations.',
      type: 'keyword_cluster',
      category: 'seo',
      channel: 'web',
      outputLabel: 'Keyword map',
      executionStage: 'strategy',
      source: 'system',
      status: 'evaluating',
      impact: 5,
      effort: 3,
      confidence: 4,
      goal_fit: 5,
      rationale: `Why this exists: The site has a blog surface but no clear keyword map behind it.\nWhy this priority: Strong SEO structure determines what content Northstar should create next.\nBusiness outcome: A better cluster map should turn expertise into compounding acquisition work.`,
      dependencies: ['t1'],
      actor: 'northstar',
      needsFounderAction: false,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't3',
      title: 'Draft blog brief: positioning for founder teams',
      description: 'Create one blog brief with angle, outline, intent, and internal links. Publishing is not included in v1.',
      type: 'blog_brief',
      category: 'content',
      channel: 'web',
      outputLabel: 'Blog brief',
      executionStage: 'ready_for_review',
      source: 'system',
      status: 'waiting_for_approval',
      impact: 4,
      effort: 2,
      confidence: 5,
      goal_fit: 5,
      rationale: `Why this exists: Northstar should create founder-approvable work, not just analysis.\nWhy this priority: The brief is ready and only needs a founder decision to move forward.\nBusiness outcome: Approved content assets give the company a repeatable content engine with less founder drafting time.`,
      dependencies: ['t2'],
      actor: 'founder',
      needsFounderAction: true,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't4',
      title: 'Scan 3 closest competitors',
      description: 'Compare messaging, content depth, and CTA structure against likely competitors.',
      type: 'competitor_scan',
      category: 'research',
      channel: 'internal',
      outputLabel: 'Competitor framing summary',
      executionStage: 'generated',
      source: 'system',
      status: 'in_progress',
      impact: 4,
      effort: 3,
      confidence: 3,
      goal_fit: 4,
      rationale: `Why this exists: Northstar needs sharper market context before tightening positioning recommendations.\nWhy this priority: Competitive context is actively informing homepage and GTM decisions.\nBusiness outcome: Better differentiation should improve win rate and content distinctiveness.`,
      dependencies: [],
      actor: 'northstar',
      needsFounderAction: false,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't5',
      title: 'Generate X launch post set for founders',
      description: 'Create a channel-aware set of short X posts that translate the company perspective into launch-ready founder language.',
      type: 'x_post_set',
      category: 'social',
      channel: 'x',
      outputLabel: 'Social post set',
      executionStage: 'ready_for_review',
      source: 'user',
      status: 'waiting_for_approval',
      impact: 4,
      effort: 2,
      confidence: 4,
      goal_fit: 4,
      rationale: `Why this exists: The founder wants ready-to-review launch content, not just strategy notes.\nWhy this priority: Social execution can move quickly once the messaging system is coherent enough to reuse.\nBusiness outcome: A specific X set gives the founder reviewable distribution assets tied to the current narrative.`,
      dependencies: [],
      actor: 'founder',
      needsFounderAction: true,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't6',
      title: 'Rewrite meta titles and descriptions',
      description: 'Update metadata for the homepage and service pages once the message hierarchy is clearer.',
      type: 'meta_rewrite',
      category: 'seo',
      channel: 'web',
      outputLabel: 'Metadata pass',
      executionStage: 'strategy',
      source: 'system',
      status: 'blocked',
      impact: 4,
      effort: 2,
      confidence: 3,
      goal_fit: 4,
      rationale: `Why this exists: Metadata should reflect the sharper positioning once headline decisions land.\nWhy this priority: The work matters, but it is correctly blocked behind homepage and keyword decisions.\nBusiness outcome: Better metadata should improve search clickthrough without creating rework.`,
      dependencies: ['t1', 't2'],
      actor: 'northstar',
      needsFounderAction: false,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't7',
      title: 'Generate visual brief for launch illustration',
      description: 'Create an illustration prompt and visual brief that a designer or image model can use for the launch post set.',
      type: 'illustration_brief',
      category: 'social',
      channel: 'instagram',
      outputLabel: 'Visual brief',
      executionStage: 'generated',
      source: 'user',
      status: 'inbox',
      impact: 3,
      effort: 2,
      confidence: 4,
      goal_fit: 3,
      rationale: `Why this exists: Social execution should include a visual direction, not just copy.\nWhy this priority: The visual brief depends on the content angle, but it is still valuable to queue early.\nBusiness outcome: Clear visual guidance speeds up creative production and keeps social assets on brand.`,
      dependencies: [],
      actor: 'northstar',
      needsFounderAction: false,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't8',
      title: 'Confirm ICP and primary acquisition channel',
      description: 'Answer the follow-up prompts so Northstar can lock the GTM plan against the right buyer and channel.',
      type: 'founder_input',
      category: 'gtm',
      channel: 'internal',
      outputLabel: 'Founder input',
      executionStage: 'waiting_on_founder',
      source: 'system',
      status: 'waiting_on_founder',
      impact: 5,
      effort: 1,
      confidence: 5,
      goal_fit: 5,
      rationale: `Why this exists: Northstar should not finalize the growth system from website copy alone.\nWhy this priority: Founder answers unlock better prioritization across every downstream task.\nBusiness outcome: Clear ICP and channel choices reduce wasted work and improve the quality of generated execution.`,
      dependencies: [],
      actor: 'founder',
      needsFounderAction: true,
      owner_type: 'user',
    }),
    scoreTask({
      id: 't9',
      title: 'Draft founder follow-up email for pilot leads',
      description: 'Write a reusable email template for warm pilot conversations, with two variants based on buying intent.',
      type: 'email_template',
      category: 'crm',
      channel: 'email',
      outputLabel: 'Email template',
      executionStage: 'generated',
      source: 'system',
      status: 'planned',
      impact: 4,
      effort: 2,
      confidence: 4,
      goal_fit: 4,
      rationale: `Why this exists: Northstar should help the founder move real conversations, not just create content.\nWhy this priority: Warm follow-up is execution work with a short path to business value.\nBusiness outcome: Better follow-up quality should improve pilot conversion and founder response speed.`,
      dependencies: [],
      actor: 'northstar',
      needsFounderAction: false,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't10',
      title: 'Prepare user interview outreach message',
      description: 'Generate a channel-aware outreach draft for recruiting five users into feedback calls.',
      type: 'user_research_outreach',
      category: 'research',
      channel: 'email',
      outputLabel: 'Outreach draft',
      executionStage: 'ready_to_send',
      source: 'system',
      status: 'planned',
      impact: 4,
      effort: 2,
      confidence: 4,
      goal_fit: 4,
      rationale: `Why this exists: User research needs actual outreach copy and scheduling support, not just a note to do interviews.\nWhy this priority: The founder can approve and use this quickly to unblock customer feedback.\nBusiness outcome: Faster outreach should increase the speed and quality of research inputs into the roadmap and messaging.`,
      dependencies: [],
      actor: 'northstar',
      needsFounderAction: false,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't11',
      title: 'Draft founder narrative asset for LinkedIn',
      description: 'Create a founder-led narrative post that explains the problem Northstar solves and why the workflow changed.',
      type: 'linkedin_post_set',
      category: 'content',
      channel: 'linkedin',
      outputLabel: 'Founder narrative asset',
      executionStage: 'generated',
      source: 'system',
      status: 'planned',
      impact: 4,
      effort: 2,
      confidence: 4,
      goal_fit: 4,
      rationale: `Why this exists: Founder narrative assets should be reusable across content and social, not improvised each time.\nWhy this priority: It supports both distribution and message consistency once the product story is clearer.\nBusiness outcome: A sharper founder narrative improves positioning consistency across channels and outbound conversations.`,
      dependencies: ['t1'],
      actor: 'northstar',
      needsFounderAction: false,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't12',
      title: 'Draft landing page copy for the pilot offer',
      description: 'Generate landing page copy blocks for a focused pilot page: headline, proof, CTA, and FAQ.',
      type: 'homepage_copy_suggestion',
      category: 'content',
      channel: 'web',
      outputLabel: 'Landing page copy',
      executionStage: 'ready_for_review',
      source: 'system',
      status: 'waiting_for_approval',
      impact: 4,
      effort: 2,
      confidence: 4,
      goal_fit: 5,
      rationale: `Why this exists: Content work should include destination pages, not just briefs and posts.\nWhy this priority: A focused landing page is close to revenue and easier to approve than a full site rewrite.\nBusiness outcome: Better landing page copy should improve conversion on the pilot offer and reduce founder writing time.`,
      dependencies: ['t1'],
      actor: 'founder',
      needsFounderAction: true,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't13',
      title: 'Prepare outbound sequence for warm leads',
      description: 'Create a short outreach sequence with first-touch, bump, and follow-up variants for warm CRM leads.',
      type: 'outreach_sequence',
      category: 'crm',
      channel: 'email',
      outputLabel: 'Outreach sequence',
      executionStage: 'ready_to_send',
      source: 'system',
      status: 'waiting_for_approval',
      impact: 4,
      effort: 2,
      confidence: 4,
      goal_fit: 4,
      rationale: `Why this exists: CRM work should include actual outbound drafts, not just contact records and next-action notes.\nWhy this priority: Warm lead follow-up is execution work with a short path to pipeline movement.\nBusiness outcome: A reviewed send-ready sequence should improve lead response rate and founder consistency.`,
      dependencies: ['t9'],
      actor: 'founder',
      needsFounderAction: true,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't14',
      title: 'Synthesize interview feedback into a learning loop',
      description: 'Turn recent user conversations into structured insights, objections, and next test ideas for the product and messaging.',
      type: 'research_summary',
      category: 'research',
      channel: 'internal',
      outputLabel: 'Feedback synthesis',
      executionStage: 'generated',
      source: 'system',
      status: 'planned',
      impact: 4,
      effort: 2,
      confidence: 4,
      goal_fit: 4,
      rationale: `Why this exists: Research should produce structured learning loops, not isolated notes.\nWhy this priority: The founder can use synthesis immediately to refine the roadmap, messaging, and outreach.\nBusiness outcome: Better synthesis should shorten the loop between user feedback and product or GTM improvements.`,
      dependencies: ['t10'],
      actor: 'northstar',
      needsFounderAction: false,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't15',
      title: 'Recommend two feature wedges for the pilot offer',
      description: 'Translate founder objections, approval friction, and execution gaps into two product-facing feature suggestions with clear GTM leverage.',
      type: 'competitor_scan',
      category: 'product_signal',
      channel: 'internal',
      outputLabel: 'Feature suggestion brief',
      executionStage: 'strategy',
      source: 'system',
      status: 'planned',
      impact: 4,
      effort: 2,
      confidence: 4,
      goal_fit: 4,
      rationale: `Why this exists: Non-technical founders need product suggestions tied to adoption and execution friction, not a disconnected backlog.\nWhy this priority: The team already has enough signal from approvals and outreach to identify the next useful product wedge.\nBusiness outcome: Better product suggestions should improve activation, demo clarity, and the quality of future execution loops.`,
      dependencies: ['t14'],
      actor: 'northstar',
      needsFounderAction: false,
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't16',
      title: 'Prepare WhatsApp founder control-surface concept',
      description: 'Define the command surface, approval checkpoints, and board sync expectations for a later WhatsApp control path.',
      type: 'integration_setup',
      category: 'integration',
      channel: 'whatsapp',
      outputLabel: 'Control-surface concept',
      executionStage: 'strategy',
      source: 'system',
      status: 'inbox',
      impact: 3,
      effort: 2,
      confidence: 3,
      goal_fit: 4,
      rationale: `Why this exists: Founders should eventually control Northstar from communication surfaces they already use.\nWhy this priority: It belongs behind the current core product work, but the architecture should be explicit early.\nBusiness outcome: A clearer control-surface concept should reduce rework when chat interfaces become a real distribution path.`,
      dependencies: [],
      actor: 'northstar',
      needsFounderAction: false,
      owner_type: 'agent',
    }),
  ],
  artifacts: [
    {
      id: 'art_1',
      taskId: 't3',
      type: 'blog_brief',
      title: 'Blog Brief: How founder-led teams can turn positioning into a content system',
      content: `Objective\nCreate a blog post that helps founder-led teams understand why positioning should come before content volume.\n\nSearch intent\nInformational and strategic. Readers want a framework they can apply immediately.\n\nProposed angle\nThe fastest path to a sustainable content engine is not more content. It is a tighter message, a sharper point of view, and a repeatable structure for turning expertise into assets.\n\nOutline\n1. Why content stalls when positioning is vague\n2. The three signals of a clear message\n3. How to translate expertise into SEO topics\n4. A simple weekly operating rhythm\n5. What to measure in the first 30 days\n\nInternal links\n- /services\n- /blog\n- /contact\n\nCTA\nInvite readers to request a positioning audit or content plan.`,
      channel: 'web',
      deliveryStage: 'ready_for_review',
      status: 'needs_review',
      createdAt: minutesAgo(90),
    },
    {
      id: 'art_2',
      taskId: 't5',
      type: 'social_post_set',
      title: 'X Launch Set: founder-led growth hooks',
      content: `# X Launch Set\n\n## Channel context\nUse this set for X. Keep the tone sharp, specific, and operator-led.\n\n## Post 1\nMost growth systems fail before channel execution.\nThey fail because the company story is still fuzzy.\n\n## Post 2\nA founder operating system should not stop at priorities.\nIt should turn company context into work, drafts, approvals, and shipping momentum.\n\n## Post 3\nNorthstar is built for the founder who does not want another recommendation engine.\nThey want the next move, the draft, and the review step in one place.\n\n## CTA\nInvite people to reply with the biggest growth bottleneck they are trying to fix right now.`,
      channel: 'x',
      deliveryStage: 'ready_for_review',
      status: 'needs_review',
      createdAt: minutesAgo(44),
    },
    {
      id: 'art_3',
      taskId: 't12',
      type: 'website_copy',
      title: 'Pilot Landing Page Copy Draft',
      content: `# Pilot Landing Page\n\n## Headline\nNorthstar turns founder context into visible growth work, reviewable drafts, and an operating board that stays usable.\n\n## Supporting copy\nFor non-technical founders who need a system for GTM execution, not another stream of recommendations.\n\n## Proof block\nSee what Northstar is doing, what the founder needs to review, and which tasks are ready to move.\n\n## CTA\nStart with your website and open a founder-ready board.\n\n## FAQ\nWhat gets generated first?\nHow do approvals work?\nCan I connect email and social channels later?`,
      channel: 'web',
      deliveryStage: 'ready_for_review',
      summary: 'A landing page draft with headline, supporting copy, proof, CTA, and FAQ blocks.',
      status: 'needs_review',
      createdAt: minutesAgo(28),
    },
    {
      id: 'art_4',
      taskId: 't13',
      type: 'outreach_sequence',
      title: 'Warm Lead Outreach Sequence',
      content: `# Warm Lead Sequence\n\n## First touch\nHi {{first_name}}, I wanted to send the clearest snapshot of how Northstar now handles planning, approvals, and execution for founder teams.\n\n## Bump\nSharing this in case the timing is better now. The main update is that the workflow no longer stops at recommendations. It creates reviewable outputs and keeps founder decisions visible.\n\n## Final follow-up\nIf helpful, I can send a short walkthrough focused on your current GTM bottleneck and where Northstar would slot in.`,
      channel: 'email',
      deliveryStage: 'ready_to_send',
      summary: 'A three-step warm lead sequence with concise founder-friendly copy.',
      status: 'ready_to_send',
      createdAt: minutesAgo(18),
    },
    {
      id: 'art_5',
      taskId: 't14',
      type: 'research_summary',
      title: 'Founder Feedback Synthesis',
      content: `# Feedback Synthesis\n\n## Core patterns\n- Founders want execution and approvals in one place.\n- Generic AI output creates more review work, not less.\n- Outreach and content are valuable only when they are specific to the business.\n\n## Repeated objections\n- Concern about noisy automation.\n- Fear of low-quality generic copy.\n- Need for clean founder-vs-agent separation.\n\n## Next tests\n1. Show send-ready states inside CRM and research workflows.\n2. Make channel-specific output clearer on board cards.\n3. Add lightweight publishing and send review scaffolding.`,
      channel: 'internal',
      deliveryStage: 'generated',
      summary: 'Structured learning loop from recent interviews, objections, and proposed next tests.',
      status: 'draft',
      createdAt: minutesAgo(12),
    },
  ],
  approvals: [
    {
      id: 'appr_1',
      taskId: 't3',
      status: 'pending',
      requestedAt: minutesAgo(80),
      note: 'Waiting for founder approval before marking the blog brief as ready to hand off.',
    },
    {
      id: 'appr_2',
      taskId: 't5',
      status: 'pending',
      requestedAt: minutesAgo(38),
      note: 'Review this X post set before it moves into scheduling or publishing.',
    },
    {
      id: 'appr_3',
      taskId: 't12',
      status: 'pending',
      requestedAt: minutesAgo(26),
      note: 'Review the landing page copy before it moves into implementation.',
    },
    {
      id: 'appr_4',
      taskId: 't13',
      status: 'pending',
      requestedAt: minutesAgo(16),
      note: 'Review this outreach sequence before it becomes send-ready.',
    },
  ],
  comments: [
    {
      id: 'c1',
      taskId: 't5',
      author: 'Founder',
      body: 'Prioritize this after the homepage message lands. I want the social copy to reflect the same narrative.',
      createdAt: minutesAgo(30),
    },
  ],
  agentRuns: [
    {
      id: 'run_1',
      projectId: 'prj_1',
      status: 'completed',
      summary: 'Analyzed homepage plus key pages and generated the initial backlog.',
      startedAt: minutesAgo(150),
      finishedAt: minutesAgo(140),
    },
    {
      id: 'run_2',
      projectId: 'prj_1',
      taskId: 't3',
      status: 'running',
      summary: 'Drafting the first blog brief artifact.',
      startedAt: minutesAgo(85),
    },
  ],
  goals: [
    {
      id: 'goal_1',
      title: 'Increase qualified inbound demand',
      metric: 'Qualified demos',
      target: '+30% in 60 days',
      horizon: 'This quarter',
      summary: 'Use clearer positioning plus SEO and founder-led content to generate more relevant conversations.',
    },
    {
      id: 'goal_2',
      title: 'Tighten the founder narrative',
      metric: 'Homepage conversion quality',
      target: 'Lift CTA conversion confidence',
      horizon: 'This month',
      summary: 'Clarify who the company serves, why it wins, and what action the site should drive next.',
    },
  ],
  initiatives: [
    {
      id: 'init_1',
      title: 'Message clarity sprint',
      category: 'website',
      status: 'active',
      summary: 'Refresh homepage structure, proof hierarchy, and CTA clarity.',
      linkedTaskIds: ['t1', 't6'],
    },
    {
      id: 'init_2',
      title: 'Organic demand engine',
      category: 'seo',
      status: 'active',
      summary: 'Turn positioning into keyword clusters, briefs, and structured content output.',
      linkedTaskIds: ['t2', 't3'],
    },
    {
      id: 'init_3',
      title: 'Founder signal loop',
      category: 'social',
      status: 'planned',
      summary: 'Use short-form social to test angles and support the GTM narrative.',
      linkedTaskIds: ['t5', 't7'],
    },
  ],
  executionProviders: [
    {
      id: 'northstar_cli',
      name: 'Northstar CLI',
      authType: 'cli',
      status: 'available',
      description: 'Use Northstar against the founder\'s current CLI or local model setup.',
      modelHint: 'Current local or CLI model',
      isDefault: true,
    },
    {
      id: 'openai',
      name: 'OpenAI',
      authType: 'api_key',
      status: 'needs_key',
      description: 'Generate assets through an OpenAI-backed execution path.',
      modelHint: 'GPT-5 family',
      isDefault: false,
    },
    {
      id: 'anthropic',
      name: 'Anthropic',
      authType: 'api_key',
      status: 'needs_key',
      description: 'Run Northstar generation through Claude models.',
      modelHint: 'Claude 4.x',
      isDefault: false,
    },
    {
      id: 'kimi',
      name: 'Kimi',
      authType: 'api_key',
      status: 'needs_key',
      description: 'Use Kimi when the founder prefers Moonshot\'s stack.',
      modelHint: 'Kimi latest',
      isDefault: false,
    },
    {
      id: 'minimax',
      name: 'MiniMax',
      authType: 'api_key',
      status: 'needs_key',
      description: 'Use MiniMax for teams standardizing there.',
      modelHint: 'MiniMax latest',
      isDefault: false,
    },
  ],
  activeProviderId: 'northstar_cli',
  integrations: [
    {
      id: 'int_1',
      key: 'x',
      name: 'X',
      category: 'social',
      authType: 'api_key',
      status: 'needs_key',
      description: 'Route post drafts and approval-ready social sets into the platform.',
      credentialLabel: 'X API key',
    },
    {
      id: 'int_2',
      key: 'instagram',
      name: 'Instagram',
      category: 'social',
      authType: 'api_key',
      status: 'planned',
      description: 'Support visual content planning and later publishing workflows.',
      credentialLabel: 'Instagram token',
    },
    {
      id: 'int_3',
      key: 'google_workspace',
      name: 'Google Workspace',
      category: 'productivity',
      authType: 'api_key',
      status: 'connected',
      description: 'Unlock Gmail, Drive, and shared founder workspace context.',
      credentialLabel: 'Workspace key',
      connectedAs: 'founder@acme-studio.com',
      maskedSecret: 'gwsp...7a32',
      connectedAt: minutesAgo(240),
      lastSyncAt: minutesAgo(18),
    },
    {
      id: 'int_4',
      key: 'gmail',
      name: 'Gmail',
      category: 'productivity',
      authType: 'api_key',
      status: 'connected',
      description: 'Use founder inbox context for outreach tasks and lightweight CRM follow-up.',
      credentialLabel: 'Gmail token',
      connectedAs: 'founder@acme-studio.com',
      maskedSecret: 'gmai...1d20',
      connectedAt: minutesAgo(240),
      lastSyncAt: minutesAgo(18),
    },
    {
      id: 'int_5',
      key: 'google_drive',
      name: 'Google Drive',
      category: 'productivity',
      authType: 'api_key',
      status: 'connected',
      description: 'Store generated assets, research notes, and approved artifacts.',
      credentialLabel: 'Drive token',
      connectedAs: 'Acme Studio Drive',
      maskedSecret: 'driv...9cf2',
      connectedAt: minutesAgo(240),
      lastSyncAt: minutesAgo(42),
    },
    {
      id: 'int_6',
      name: 'Intercom',
      key: 'intercom',
      category: 'support',
      authType: 'api_key',
      status: 'needs_key',
      description: 'Pull customer language and support conversations into research and GTM planning.',
      credentialLabel: 'Intercom token',
    },
    {
      id: 'int_7',
      key: 'threads',
      name: 'Threads',
      category: 'social',
      authType: 'api_key',
      status: 'planned',
      description: 'Prepare founder-ready shortform variants for Threads.',
      credentialLabel: 'Threads token',
    },
    {
      id: 'int_8',
      key: 'image_generation',
      name: 'Image generation',
      category: 'social',
      authType: 'api_key',
      status: 'planned',
      description: 'Turn illustration prompts into a usable visual workflow later.',
      credentialLabel: 'Image API key',
    },
    {
      id: 'int_9',
      key: 'whatsapp',
      name: 'WhatsApp',
      category: 'crm',
      authType: 'api_key',
      status: 'planned',
      description: 'Future founder control surface for approvals, follow-ups, and lightweight command handling.',
      credentialLabel: 'WhatsApp token',
    },
    {
      id: 'int_10',
      key: 'telegram',
      name: 'Telegram',
      category: 'crm',
      authType: 'api_key',
      status: 'planned',
      description: 'Future chat control surface for board triage, approvals, and founder prompts.',
      credentialLabel: 'Telegram token',
    },
  ],
  crmContacts: [
    {
      id: 'crm_1',
      name: 'Nora Li',
      company: 'Quarry SaaS',
      stage: 'warm',
      nextAction: 'Send the founder story audit follow-up on Friday.',
      owner: 'Founder',
      linkedTaskIds: ['t9', 't13'],
    },
    {
      id: 'crm_2',
      name: 'Ari Patel',
      company: 'Launchbench',
      stage: 'interviewing',
      nextAction: 'Schedule a 20-minute user interview on homepage objections.',
      owner: 'Northstar',
      linkedTaskIds: ['t10', 't14'],
    },
    {
      id: 'crm_3',
      name: 'Jordan Kim',
      company: 'Orbit Labs',
      stage: 'pilot',
      nextAction: 'Review pilot results and create retention talking points.',
      owner: 'Founder',
      linkedTaskIds: ['t12', 't15'],
    },
  ],
  researchNotes: [
    {
      id: 'note_1',
      title: 'Competitor positioning snapshot',
      summary: 'Most nearby alternatives lead with generic growth language and weak proof hierarchy.',
      type: 'competitor',
      createdAt: minutesAgo(95),
      linkedTaskIds: ['t4', 't15'],
      linkedInitiativeIds: ['init_1'],
    },
    {
      id: 'note_2',
      title: 'Founder interview pattern',
      summary: 'Teams struggling with growth usually mention message clarity before channel execution.',
      type: 'interview',
      createdAt: minutesAgo(55),
      linkedTaskIds: ['t8', 't10', 't14'],
      linkedInitiativeIds: ['init_2', 'init_3'],
    },
  ],
};

export const redesignBuildPlan: BuildPhase[] = [
  {
    id: 'phase_shell',
    title: 'Shell and navigation cleanup',
    status: 'active',
    goal: 'Strip the product shell down to a calm board-first workspace with clear navigation and one obvious next action.',
    tasks: [
      {
        id: 'task_build_dashboard',
        title: 'Ship build progress dashboard',
        status: 'in_progress',
        owner: 'codex',
        summary: 'Expose what is being built, what is blocked, and what comes next inside the product shell.',
        nextStep: 'Wire the dashboard into the current command-center surface and keep the summary scannable.',
      },
      {
        id: 'task_sidebar_cleanup',
        title: 'Simplify left navigation',
        status: 'next',
        owner: 'codex',
        summary: 'Reduce the sidebar to the product surfaces that matter and remove wave-focus narrative modules.',
        nextStep: 'Replace grouped founder-ops taxonomy with a quieter top-level nav.',
      },
      {
        id: 'task_topbar_cleanup',
        title: 'Simplify top bar',
        status: 'planned',
        owner: 'codex',
        summary: 'Keep only workspace switcher, search, connection state, and a single primary action.',
        nextStep: 'Remove competing quick actions and operator-strip noise.',
      },
    ],
  },
  {
    id: 'phase_board',
    title: 'Board-first landing page',
    status: 'up_next',
    goal: 'Make the first screen answer what matters now, what needs approval, what is live, and what the next action is.',
    tasks: [
      {
        id: 'task_board_sections',
        title: 'Rebuild board above the fold',
        status: 'next',
        owner: 'codex',
        summary: 'Limit the first screen to Today, Needs approval, Live campaigns, and Performance snapshot.',
        nextStep: 'Replace multi-surface overview blocks with four compact operational sections.',
      },
      {
        id: 'task_board_default',
        title: 'Keep board as default landing',
        status: 'planned',
        owner: 'codex',
        summary: 'Users with an existing workspace should land in execution instead of explanation.',
        nextStep: 'Make the shell open on Board while preserving onboarding when no project exists.',
      },
    ],
  },
  {
    id: 'phase_approvals',
    title: 'Approval flow cleanup',
    status: 'queued',
    goal: 'Make review frictionless so the founder can approve or request changes without hunting for context.',
    tasks: [
      {
        id: 'task_approval_list',
        title: 'Tighten approvals list',
        status: 'planned',
        owner: 'codex',
        summary: 'Show title, type, why it matters, preview, and approve/request-changes actions in one glance.',
        nextStep: 'Reduce approval cards to the smallest reviewable unit.',
      },
      {
        id: 'task_approval_detail',
        title: 'Simplify approval detail',
        status: 'planned',
        owner: 'codex',
        summary: 'Keep the draft, goal, audience, and actions visible without burying decision buttons.',
        nextStep: 'Trim the drawer/modal copy and surface the core decision context first.',
      },
    ],
  },
  {
    id: 'phase_campaigns',
    title: 'Campaign surface',
    status: 'queued',
    goal: 'Introduce a simple campaigns view only after the board and approvals are calm and trustworthy.',
    tasks: [
      {
        id: 'task_campaign_list',
        title: 'Model campaign list',
        status: 'planned',
        owner: 'codex',
        summary: 'Create a lightweight campaign list tied to board tasks and assets instead of inventing a second product.',
        nextStep: 'Define the smallest useful campaign object from existing tasks and artifacts.',
      },
      {
        id: 'task_campaign_detail',
        title: 'Group assets by campaign',
        status: 'blocked',
        owner: 'codex',
        summary: 'Campaign detail should wait until the data model is cleaned up and the board-first flow is stable.',
        nextStep: 'Do not expand this until shell and board cleanup are finished.',
      },
    ],
  },
];
