import type { AppState, Task } from './types';

const now = new Date();
const minutesAgo = (mins: number) => new Date(now.getTime() - mins * 60_000).toISOString();

const scoreTask = (task: Omit<Task, 'priority_score' | 'created_at' | 'updated_at'>): Task => ({
  ...task,
  priority_score: Number(((task.impact * task.confidence * task.goal_fit) / task.effort).toFixed(2)),
  created_at: minutesAgo(60),
  updated_at: minutesAgo(5),
});

export const demoState: AppState = {
  workspace: {
    id: 'ws_1',
    name: 'North Star Foundry',
    createdAt: minutesAgo(7_200),
  },
  project: {
    id: 'prj_1',
    workspaceId: 'ws_1',
    name: 'Acme Studio',
    websiteUrl: 'https://acme-studio.com',
    createdAt: minutesAgo(7_100),
  },
  snapshot: {
    id: 'snap_1',
    projectId: 'prj_1',
    capturedAt: minutesAgo(120),
    homepageTitle: 'Strategic design and growth for modern teams',
    homepageSummary: 'The homepage positions the company as a design and growth partner for ambitious teams, but it under-explains who the service is for and what the strongest conversion path should be.',
    pages: [
      {
        url: 'https://acme-studio.com/',
        title: 'Home',
        summary: 'Clear positioning, but weak CTA hierarchy.',
      },
      {
        url: 'https://acme-studio.com/services',
        title: 'Services',
        summary: 'Lists services without tying them to measurable outcomes.',
      },
      {
        url: 'https://acme-studio.com/blog',
        title: 'Blog',
        summary: 'Has the right content channel, but no keyword strategy.',
      },
    ],
  },
  profile: {
    id: 'cmp_1',
    projectId: 'prj_1',
    companyName: 'Acme Studio',
    summary: 'A boutique growth and design studio helping founder-led businesses improve conversion, visibility, and positioning.',
    guessedIcp: 'Founder-led SaaS and service businesses with 1-20 people that need clearer positioning and a repeatable content engine.',
    keyPages: ['Home', 'Services', 'Blog'],
    opportunities: [
      'Homepage copy can sharpen the value proposition and CTA hierarchy.',
      'SEO clusters around founder pain points are underdeveloped.',
      'LinkedIn thought leadership can turn expertise into top-of-funnel demand.',
      'The blog can support comparison and educational search intent.',
    ],
  },
  tasks: [
    scoreTask({
      id: 't1',
      title: 'Audit homepage message hierarchy',
      description: 'Review the hero, benefit stack, and calls-to-action so the homepage explains the company faster and with more conviction.',
      type: 'homepage_copy_suggestion',
      source: 'system',
      status: 'planned',
      impact: 5,
      effort: 2,
      confidence: 4,
      goal_fit: 5,
      rationale: 'Improves clarity and conversion on the highest-traffic page.',
      dependencies: [],
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't2',
      title: 'Build keyword cluster around founder-led growth',
      description: 'Group target keywords into SEO clusters focused on positioning, conversion, and content operations.',
      type: 'keyword_cluster',
      source: 'system',
      status: 'evaluating',
      impact: 5,
      effort: 3,
      confidence: 4,
      goal_fit: 5,
      rationale: 'Creates the content map that will guide future blog briefs.',
      dependencies: ['t1'],
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't3',
      title: 'Draft blog brief: positioning for founder teams',
      description: 'Create one blog brief with angle, outline, intent, and internal links. Publishing is not included in v1.',
      type: 'blog_brief',
      source: 'system',
      status: 'waiting_for_approval',
      impact: 4,
      effort: 2,
      confidence: 5,
      goal_fit: 5,
      rationale: 'This is the first artifact the founder can approve and hand off.',
      dependencies: ['t2'],
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't4',
      title: 'Scan 3 closest competitors',
      description: 'Compare messaging, content depth, and CTA structure against likely competitors.',
      type: 'competitor_scan',
      source: 'system',
      status: 'in_progress',
      impact: 4,
      effort: 3,
      confidence: 3,
      goal_fit: 4,
      rationale: 'Gives context for differentiating the company story and content plan.',
      dependencies: [],
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't5',
      title: 'Write LinkedIn post set for founders',
      description: 'Create a small set of social posts that translate the company perspective into founder-friendly language.',
      type: 'linkedin_post_set',
      source: 'user',
      status: 'inbox',
      impact: 3,
      effort: 2,
      confidence: 4,
      goal_fit: 4,
      rationale: 'User-added task with good topical fit and a clear content payoff.',
      dependencies: [],
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't6',
      title: 'Rewrite meta titles and descriptions',
      description: 'Update metadata for the homepage and service pages once the message hierarchy is clearer.',
      type: 'meta_rewrite',
      source: 'system',
      status: 'blocked',
      impact: 4,
      effort: 2,
      confidence: 3,
      goal_fit: 4,
      rationale: 'Depends on the homepage and keyword strategy being settled.',
      dependencies: ['t1', 't2'],
      owner_type: 'agent',
    }),
    scoreTask({
      id: 't7',
      title: 'Create X post set for product story',
      description: 'Generate concise social posts for thought leadership and launch momentum.',
      type: 'x_post_set',
      source: 'user',
      status: 'inbox',
      impact: 2,
      effort: 1,
      confidence: 4,
      goal_fit: 3,
      rationale: 'Fast to produce, but slightly lower goal fit than the SEO work.',
      dependencies: [],
      owner_type: 'agent',
    }),
  ],
  artifacts: [
    {
      id: 'art_1',
      taskId: 't3',
      type: 'blog_brief',
      title: 'Blog Brief: How founder-led teams can turn positioning into a content system',
      content: `Objective\nCreate a blog post that helps founder-led teams understand why positioning should come before content volume.\n\nSearch intent\nInformational and strategic. Readers want a framework they can apply immediately.\n\nProposed angle\nThe fastest path to a sustainable content engine is not more content. It is a tighter message, a sharper point of view, and a repeatable structure for turning expertise into assets.\n\nOutline\n1. Why content stalls when positioning is vague\n2. The three signals of a clear message\n3. How to translate expertise into SEO topics\n4. A simple weekly operating rhythm\n5. What to measure in the first 30 days\n\nInternal links\n- /services\n- /blog\n- /contact\n\nCTA\nInvite readers to request a positioning audit or content plan.`,
      status: 'needs_review',
      createdAt: minutesAgo(90),
    },
  ],
  approvals: [
    {
      id: 'appr_1',
      taskId: 't3',
      status: 'pending',
      requestedAt: minutesAgo(80),
      note: 'Waiting for founder approval before marking the blog brief as ready to hand off.',
    },
  ],
  comments: [
    {
      id: 'c1',
      taskId: 't5',
      author: 'Founder',
      body: 'Prioritize this after the homepage message lands. I want the social copy to reflect the same narrative.',
      createdAt: minutesAgo(30),
    },
  ],
  agentRuns: [
    {
      id: 'run_1',
      projectId: 'prj_1',
      status: 'completed',
      summary: 'Analyzed homepage plus key pages and generated the initial backlog.',
      startedAt: minutesAgo(150),
      finishedAt: minutesAgo(140),
    },
    {
      id: 'run_2',
      projectId: 'prj_1',
      taskId: 't3',
      status: 'running',
      summary: 'Drafting the first blog brief artifact.',
      startedAt: minutesAgo(85),
    },
  ],
};
